name: xnn
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - pylint
      - pytest-cov
      - black
      - ipykernel
      - tqdm
      - pre-commit
      - numpy
      - pandas
      - torch
      - torchvision
      - lightning[extra]
      - jsonargparse[signatures]
      - hydra-core==1.1.1
      - hydra-optuna-sweeper==1.1.1
      - optuna==2.10.0
      - grad-cam
      - streamlit==1.7.0
      - click==7.1.2
      - python-json-logger==2.0.4