name: xnn-dev
channels:
  - defaults
dependencies:
  - python=3.10.9
  - pip=23.0.1
  - pip:
      - pylint
      - pytest-cov
      - black==20.8b1
      - ipykernel
      - tqdm
      - pre-commit
      - numpy
      - pandas
      - torch
      - torchvision
      - lightning[extra]
      - jsonargparse[signatures]
      - hydra-core==1.1.1
      - hydra-optuna-sweeper==1.1.1
      - optuna==2.10.0      - opencv-python
      - matplotlib
      - grad-cam
      - streamlit==1.7.0
      - click==7.1.2
      - python-json-logger==2.0.4