train:
  params:
    epochs: 1
    batch_size: 32
    learning_rate: 0.003
  transforms:
    image_size: 224 

data_paths:
  train_data_path: "data/train"
  val_data_path: "data/val"
  test_data_path: "data/test"
  meta_data_path: "data/dataset_remove_relative_path.csv"