# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: "**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          $CONDA/bin/conda env update --file conda-dev.yaml
          source /usr/share/miniconda/bin/activate xnn
          $CONDA/bin/conda info
      - name: Lint with Pylint
        run: |
          source /usr/share/miniconda/bin/activate xnn
          $CONDA/bin/conda info
          pip install pylint pytest
          pylint src --fail-under=7.0 --ignore=tests --disable=W1202
      - name: Test with pytest
        run: |
          pytest