name: Development tests

on:
  push:
    branches: "**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

  tests:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          $CONDA/bin/conda env update --file conda-dev.yaml
          source /usr/share/miniconda/bin/activate xnn
      - name: Lint with Pylint
        run: |
          source /usr/share/miniconda/bin/activate xnn
          pip install pylint pytest
          pylint src --fail-under=7.0 --ignore=tests --disable=W1202
      # - name: Test with pytest
      #   run: |
      #     pytest tests -v
